repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.2.1
    hooks:
      - id: clang-format
        args: [--style=file]

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
