name: Unit tests
on: 
  push:
    paths:
      - 'nulascript/**'
      - 'ctests/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        run: sudo apt update && sudo apt install -y cmake make

      - name: Install GTest
        run: make install-gtest

      - name: Run tests
        run: make run-tests